### ISSUE TITLE
Implement incremental polling via hyperion for delegation

### ISSUE THREAD

**Issue by tomtomcrypto** [telosnetwork/obe-indexer#23]
## Description
Currently we only full load delegations data. We want to turn that into an initial full load followed by incremental updates.

## Task

- [x] Implement incremental polling via hyperion
- [x] Figure out why first reindexing failed for delegation, no initial scan
- [x] Reindex
- [x] Check data

## Acceptance

- [x] Data is indexed incrementally and is correct
